version: "3.2"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    volumes:
      - elk_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    restart: unless-stopped
    networks:
      - elk

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elk_data:
